---
- name: Replication configuration | 1st Pt.
  mongodb_replication:
    login_host: "{{ mongodb_login_host|default('localhost') }}"
    login_port: "{{ mongodb_net_port|default(27017) }}"
    login_user: "{{ mongodb_root_admin_name }}"
    login_password: "{{ mongodb_root_admin_password }}"
    replica_set: "{{ mongodb_replication_replset }}"
    host_name: "{{ item.host_name }}"
    host_port: "{{ item.host_port|default(27017) }}"
    host_type: "{{ item.host_type|default('replica') }}"
    hidden: "{{ item.hidden|default(false) }}"
    priority: "{{ item.priority|default(1.0) }}"
    ssl: "{{ mongodb_ssl_mode != 'disabled' }}"
    ssl_certfile: "{{ mongodb_ssl_client_certfile_path if mongodb_ssl_mode != 'disabled' and mongodb_ssl_client_certfile_path else omit }}"
    ssl_keyfile: "{{ mongodb_ssl_client_keyfile_path if mongodb_ssl_mode != 'disabled' and mongodb_ssl_client_keyfile_path else omit }}"
    ssl_cacerts: "{{ mongodb_ssl_cacertfile_path if mongodb_ssl_mode != 'disabled' and mongodb_ssl_cacertfile_path else omit }}"
  with_items:
    - "{{ mongodb_replication_params|default([]) }}"
  register: mongodb_replica_init
  ignore_errors: true

- include: auth_initialization.yml
  when: mongodb_replica_init|failed

- name: Replication configuration | 2nd Pt
  mongodb_replication:
    login_host: "{{ mongodb_login_host|default('localhost') }}"
    login_port: "{{ mongodb_net_port|default(27017) }}"
    login_user: "{{ mongodb_root_admin_name }}"
    login_password: "{{ mongodb_root_admin_password }}"
    replica_set: "{{ mongodb_replication_replset }}"
    host_name: "{{ item.host_name }}"
    host_port: "{{ item.host_port|default(27017) }}"
    host_type: "{{ item.host_type|default('replica') }}"
    hidden: "{{ item.hidden|default(false) }}"
    priority: "{{ item.priority|default(1.0) }}"
    ssl: "{{ mongodb_ssl_mode != 'disabled' }}"
    ssl_certfile: "{{ mongodb_ssl_client_certfile_path if mongodb_ssl_mode != 'disabled' and mongodb_ssl_client_certfile_path else omit }}"
    ssl_keyfile: "{{ mongodb_ssl_client_keyfile_path if mongodb_ssl_mode != 'disabled' and mongodb_ssl_client_keyfile_path else omit }}"
    ssl_cacerts: "{{ mongodb_ssl_cacertfile_path if mongodb_ssl_mode != 'disabled' and mongodb_ssl_cacertfile_path else omit }}"
  when: mongodb_replica_init|failed
  with_items:
    - "{{ mongodb_replication_params|default([]) }}"
